# Generated by Django 3.2.8 on 2022-02-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='adress',
            new_name='address',
        ),
    ]
