# Generated by Django 3.2.8 on 2022-03-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220225_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.ordermodel_pizza_order',),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('DEL', 'Delivered')], default='PEN', max_length=3),
        ),
    ]
